### ISSUE TITLE
Ошибка компиляции

### ISSUE THREAD

**Issue by Ostroverkhov** [ThreadsMobileLib/edna-sdk-ios#13]
Проект под iOS 11.4
Версия XCode 12.2 (12B45b)
Версия Threads 3.6.1

Появилась такая ошибка компиляции:
<img width="874" alt="Screenshot 2020-11-19 at 14 20 15" src="https://user-images.githubusercontent.com/20270559/99660525-87083600-2a73-11eb-8097-b0d6a2df04fc.png">

**Comment by oltv00** [comment]
@Luten @ThreadsMobileLib
Не собирается библиотека в Xcode 11/12

Пробовал в
Xcode Version 11.7 (11E801a)
Xcode Version 12.2 (12B45b)
Cocoapods 1.9.3 - 1.10.0
OS - macOS Catalina 10.15.7 (19H15)

В Xcode 12 ошибка такая же как и выше.
В Xcode 11 ошибки другие и разные в зависимости от сборки на device / simulator

Тестовый проект и логи можно скачать по [ссылке](https://yadi.sk/d/CaLEkShgkmxmBg).

Подскажите, как корректно интегрировать библиотеку ?
